### ISSUE TITLE
 seek ,gulp pipe Example

### ISSUE THREAD

**Issue by ktangel** [posthtml/posthtml-include#11]
This module is supported gulp?
please give a gulp，pipe expression  usage

**Comment by michael-ciniawsky** [comment]
hi, if your problem is providing the right options.root when processing your html files take use gulp-tap to get the filepath and set it as options.root

```js
const gulp = require('gulp')

const tap = require('gulp-tap')
const posthtml = require('gulp-posthtml')

gulp.task('html', () => {
  let path
  const plugins = [ 
    require('posthtml-include')({
       root: `${path}`,
       encoding: 'utf8'
    }) 
  ]
  
  gulp.src('./src/*.html')
    .pipe(tap((file) => path = file.path))
    .pipe(posthtml(plugins))
    .pipe(gulp.dest('./dist'))
})

**Comment by ktangel** [comment]
谢谢，不过我没在用es6,能否用es5的展示
but I'm not using ES6, can use ES5  expression，Thank you,

**Comment by michael-ciniawsky** [comment]
```js
var gulp = require('gulp')

var tap = require('gulp-tap')
var posthtml = require('gulp-posthtml')

gulp.task('html', function () {
  var path
  var plugins = [ 
    require('posthtml-include')({
       root: String(path),
       encoding: 'utf8'
    }) 
  ]
  
  gulp.src('./src/*.html')
    .pipe(tap(function (file) {
        path = file.path
        return path
    })
    .pipe(posthtml(plugins))
    .pipe(gulp.dest('./dist'))
})
```

**Comment by ktangel** [comment]
Var :
<pre>
<code>
var del = require('del'),
	fs = require('fs'),
	ejs = require('gulp-ejs'),
	less = require('gulp-less'),
	gulpif = require('gulp-if'),
	util = require('./lib/util'),
	path = require('path'),
	clean = require('gulp-clean'),
	ejshelper = require('tmt-ejs-helper'),
	extender = require('gulp-html-extend'); //html模板插件
var bs = require('browser-sync').create(); // 自动刷新浏览器
var lazyImageCSS = require('gulp-lazyimagecss'); // 自动为图片样式添加 宽/高/background-size 属性
var postcss = require('gulp-postcss'); // CSS 预处理
var autoprefixer = require('gulp-autoprefixer'); // 添加 CSS 浏览器前缀
var postcssPxtorem = require('postcss-pxtorem'); // CSS 转换 `px` 为 `rem`
var posthtmlPx2rem = require('posthtml-px2rem'),
	fileinclude = require('gulp-file-include'); // 可以 include html 文件
var posthtml_import = require('posthtml-import');
var posthtml_include = require('posthtml-include');
var tap = require('gulp-tap');
var posthtml = require('gulp-posthtml'); // HTML 预处理
</code>
</pre>

Html:
src/html/upload-my.html

      
      
    <include src="_posthtml/head.html" ></include>  
    <link rel="stylesheet" type="text/css" href="../lib/datepicker/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="../lib/datepicker/jquery-ui.structure.css" />
    <link rel="stylesheet" type="text/css" href="../lib/datepicker/jquery-ui.theme.css" />
    <link rel="stylesheet" type="text/css" href="../css/style-upload-my.css">
    <title>个人中心</title>
     ......
    `<!--//this is gulp-html-extend -->`


src/html/_posthtml/head.html ：

    <link rel="stylesheet" type="text/css" href="../css/style-upload-edit.css">



Files Three:


take Code:
<pre>
<code>
    //编译 html
	function compileHtml() {
		var _path;
		var plugins = [require('posthtml-include')({
			root: String(_path),
			encoding: 'utf8'
		})];
		return gulp.src(paths.src.html)    // = ["./src/html/**/*.html","!./src/html/_*/**/*.html"];
			.pipe(tap(function(file) {
				_path = file.path;
				console.log(_path);
				return _path;
			}))
			.pipe(posthtml(plugins))
			.pipe(gulp.dest(paths.dev.html));    // = "dev/html/"
	}
</code>
</pre>
Run in gulp.series Error Log:
"The following tasks did not complete: build_dev, <parallel>, compileHtml
 Did you forget to signal async completion?"

**Comment by ktangel** [comment]
Oh... my god..

I try change var _path;
On the success of use _path to String path ；

`var _path = "./src/html/";` 

The problem lies in the tap fn return value ;
Thank you again for your patience.

**Comment by michael-ciniawsky** [comment]
@ktangel did it finally work? if not please

1.show the output of ```console.log(_path)```
2.show the hole gulpfile
3.consider posthtml-head-elements for your usecase
4.upload a example repo on github containing your setup and provide the link, so i can get my hands on it , much going on there as it seems

> Run in gulp.series Error Log:
"The following tasks did not complete: build_dev, , compileHtml
Did you forget to signal async completion?"

Thats an gulp 4 issue, what does build the build_dev task do?, i emphasize to test the compile html isolated and simplified first

**Comment by michael-ciniawsky** [comment]
:+1 kk welcome, maybe gulp-tap isn't working with gulp 4, there are major changes to the guts of gulp, i believe it's possible to access the file.path without any helpers in gulp 4 but i need to look that up again.

**Comment by michael-ciniawsky** [comment]
If you find some spare time gulp-using would be an alternative to gulp-tap, but no guarantee this plugin works with gulp 4 :)

**Comment by ktangel** [comment]
yes,I do use gulp 4,o(^▽^)o。

**Comment by ktangel** [comment]
Now I can abandon gulp-html-extend o(*￣▽￣*)ブ

**Comment by ktangel** [comment]
var _path static path,  take code it works:
<pre>
<code>
	function compileHtml() {
		var _path = paths.src.posthtml_dir;   // = "./src/html/_posthtml/"
		console.log(_path)
//		var plugins = [require('posthtml-include')({
//			root: String(_path),
//			encoding: 'utf8'
//		})];
		return gulp.src(paths.src.html)
			.pipe(extender({
				annotations: true,
				verbose: false
			}))
			.pipe(ejs(ejshelper()).on('error', function(error) {
				console.log(error.message);
			}))
			.pipe(gulpif(config.supportREM,posthtml(posthtmlPx2rem({rootValue: 20,minPixelValue: 2}))))
			.pipe(posthtml([require('posthtml-include')({root:_path,encoding: 'utf8'})]))
			.pipe(gulp.dest(paths.dev.html))
			.on('data', function() {})
			.on('end', reloadHandler);
	}
</code>
</pre>

so,Thank you again;
