### ISSUE TITLE
Include Path relative to include parent file

### ISSUE THREAD

**Issue by iamfrntdv** [posthtml/posthtml-include#12]
Let's say we have `src` folder that is root. Inside that folder we have `index.html` that includes `block/block.html`. `blocks/block-1.html` includes `elements/element-1.html`.

```
[blocks]
    | - [elements]
        |- element-1.html
    |- block-1.html
index.html

```

to make includes work we should use next include path:

```
// index.html
<include src="block/block.html">

// blocks/block-1.html
<include src="blocks/elements/element-1.html">
```

So each include path should start from root folder.

It wold be great if path could start from where html is included and not from the root

```
// index.html
<include src="block/block.html">

// blocks/block-1.html
<include src="elements/element-1.html">
```

**Comment by jescalan** [comment]
This shouldn't be too tough of a feature to add -- any interest in submitting a pull request to add it? The feature is present in [reshape-include](https://github.com/reshape/include/blob/master/lib/index.js#L22) already if you need a reference or push in the right direction 😁

**Comment by iamfrntdv** [comment]
i could submit pull request but unfortunately i don't have no idea how to implement this feature.. my JS knowledge is at the very beginning.

**Comment by jescalan** [comment]
@iamfrntdv what better time to learn than now? I'd be happy to help you through it if you have questions 😁

**Comment by iamfrntdv** [comment]
ok, i will try 😁

**Comment by michael-ciniawsky** [comment]
@iamfrntdv  The main problem here is that currently posthtml has no information about the current file it processes, like postcss does with `...process(css, { from: file })`, `...process(html, { from: 'missing' }`. There are many annoyances because of that missing feature :), atm there is not really a convenient way to add relative includes, but I want this feature aswell 😛

**Comment by iamfrntdv** [comment]
@michael-ciniawsky should we open an issue in posthtml repository?

**Comment by michael-ciniawsky** [comment]
@iamfrntdv already done :), this affects all plugins which need access to the file || file.path || file.system, I hadn't much time lately for posthtml related stuff, let me check, if I'm not completely mistaken, I have a local branch with a rough `tree.file = options.from` implementation somewhere in the abyss 😛 . Vote && join Discussion at [#188](https://github.com/posthtml/posthtml/issues/188) please

**Comment by michael-ciniawsky** [comment]
@iamfrntdv I will update it soon, we can do it with `tree.options.from`, just a patch to `posthtml-include` needed

**Comment by Scrum** [comment]
@iamfrntdv Hi, is this still an issue for you?

**Comment by iamfrntdv** [comment]
@Scrum not any more, thank you.
