### ISSUE TITLE
Ability to include non-parsed files

### ISSUE THREAD

**Issue by mrmlnc** [posthtml/posthtml-include#14]
Hello,

Do you have any plans to add the ability to include files without parsing, for example, SVG sprite or CSS?

```html
<head>
  <include src="build/styles/styles.css" raw></include>
</head>
<body>
  <include src="build/images/sprite.svg" raw></include>
</body>
```

Or I should to use `posthtml/content` with my own functions?

**Comment by jescalan** [comment]
So you can do this just by making them html-compatible. If you do `style.html`, but have the entire file just be a `style` tag, it would work fine. And the svg should work fine out of the box, since svg is compatible directly with html.

**Comment by mrmlnc** [comment]
@jescalan,

So, for example, I compiled Less to CSS file and want to include it to HTML (bit styles for small page) automatically. In this case, I find it easier to specify an attribute (`raw`) than to change the contents of a CSS file.

About SVG I wasn't thinking and simply pointed out as an example.

**Comment by michael-ciniawsky** [comment]
@mrmlnc imo `poshtml-include` should only include markup partials (`.html', `.sml`, `.pug`), either use `posthtml-content` or make a separate plugin (e.g posthtml-raw) with a `<style><raw src="file.css"></raw>` tag :)

**Comment by mrmlnc** [comment]
@michael-ciniawsky,

I assumed from the name of the plugin and his description `Include file in HTML` from `package.json`. In my understanding, I can include any file.

**Comment by voischev** [comment]
@mrmlnc good point 👍

**Comment by michael-ciniawsky** [comment]
Ok hold on a sec :), I have v2.0.0 'ready' (

- cache, 
- relative includes (tree.options.from), 
- sync/async support,
- custom parser support (tree.options.parser) => `.pug`, `.sml`

For raw includes, all `extname(src) !== '.html' || '.sml' || '.pug'` could be used, but....

**Comment by michael-ciniawsky** [comment]
If this should really be part of `posthtml-include` add a `<raw src="file.css"></raw>` tag ? 👀

**Comment by mrmlnc** [comment]
@michael-ciniawsky,

IMO, better to use attribute, because `SugarML` == `.sml || .sgr || .pikachu`.

**Comment by michael-ciniawsky** [comment]
@voischev @mrmlnc

**Comment by michael-ciniawsky** [comment]
> IMO, better to use attribute, because SugarML == .sml || .sgr || .pikachu. 

Yep, I'm aware of :), currently that isn't a problem because all other `.ext`

`extname(src) !== 'html' ? parser = tree.options.parser : parser`

the plugin assumes, you have a custom parser (tree.options.from) for that set

**Comment by michael-ciniawsky** [comment]
Wirh raws we need either another custom tag or extension whitelist for 'non-raws'

**Comment by jescalan** [comment]
The only caveat I'd want to mention here is that if you include raw content, it would need to be surrounded by another tag. So you'd need to run:

```
<style>
  <include src='whatever.css' raw>
</style>
```

I definitely would question the benefits of this over just using a stylesheet tag, but in theory it could work with posthtml if someone implemented it!

**Comment by voischev** [comment]
my concept https://github.com/posthtml/posthtml-include/pull/15

**Comment by michael-ciniawsky** [comment]
👍 mom :), meanwhile this is the current 'status' from my side

``js
// ------------------------------------
// #POSTHTML - INCLUDE - INDEX
// ------------------------------------

'use strict'

const cache = require('read-cache')

const resolve = require('path').resolve
const dirname = require('path').dirname
const extname = require('path').extname

let parser = require('posthtml-parser')

/**
 * Includes Parser
 *
 * @name parse
 * @type {Object}
 *
 * @prop sync
 * @prop async
 */
const parse = {
  /**
   * Parse Includes (sync)
   *
   * @method sync
   *
   * @param  {String} src File
   *
   * @return {Object}     Include PostHTML Tree
   */
  sync: function (node, src) {
    node.tag = false
    node.content = parser(cache.sync(src, 'utf8'))

    return node
  },
  /**
   * Parse Includes (async)
   *
   * @method async
   *
   * @param  {String} src File
   *
   * @return {Promise}    Include PostHTML Tree
   */
  async: function (node, src) {
    return cache(src, 'utf8')
      .then((src) => parser(src))
      .then((src) => {
        node.tag = false
        node.content = src
      })
  }
}

/**
 * @author Ivan Voischev <voischev.ivan@ya.ru>
 * @description PostHTML Includes Plugin
 *
 * @module posthtml-include
 * @version 2.0.0
 *
 * @requires read-cache
 * @requires posthtml-parser
 *
 * @param  {Object} options Options
 *
 * @return {Function}       Include Plugin
 */
module.exports = function (options) {
  options = options || { root: process.cwd(), relative: true, async: true }

  /**
   * Include Plugin for PostHTML
   *
   * @method posthtmlInclude
   *
   * @param  {Object} tree  PostHTML Tree
   *
   * @return {Object} tree  PostHTML Tree (Transformed)
   */
  return function posthtmlInclude (tree) {
    if (!tree.messages) tree.messages = []

    options.relative ? options.root = dirname(tree.options.from) : options.root

    const includes = []

    tree.match([ { tag: 'include' }, { tag: 'import' } ], (node) => {
      let src = resolve(options.root, node.attrs.src) || false

      extname(src) !== '.html' ? parser = tree.options.parser : parser

      if (src) {
        if (options.sync) {
          node = parse.sync(src)
        }

        includes.push(parse.async(node, src))

        tree.messages.push({ type: 'dependency', file: src })
      }

      if (!src) {
        tree.messages.push({
          type: 'warning',
          warning: `posthtml-include: ${node.attrs.src} could not be loaded`
        })
      }

      return node
    })

    return includes.length > 0 ? Promise.all(includes).then(() => tree) : tree
  }
}
```

**Comment by mrmlnc** [comment]
PostHTML plugins not have access to root context? Because `parser` option looks like Hacky solution.

**Comment by michael-ciniawsky** [comment]
@mrmlnc can you elaborate a bit more please :) 

`posthtml([]).process(html, {parser: Myparser})` => `tree.options.parser = MyParser`

**Comment by michael-ciniawsky** [comment]
@voischev the fs.existsSync check is nice 👍 , and the filter is a good solution, but why options.parse ? What is your opinion on getting the custom parser from the main Instance, when extname(src) || filter(src) ==! '.html' ? (I will test posthtml-pug and posthtml-sugarml beforehand)

**Comment by michael-ciniawsky** [comment]
I think `options`should be minimal when possible :)

```js
const options = {
   sync: Boolean// => false
   root: this.root || process.cwd()
   relative: Boolean // => true => tree.options.from
   pretty: Boolean // Add correct indent like in posthtml-import ( too be deprecated :) )
                             // (Under Consideration) 
}
```

**Comment by michael-ciniawsky** [comment]
Recursive Includes and skipping duplicates are missing atm. help wanted :D

**Comment by michael-ciniawsky** [comment]
```js

function filter (ext) {
   return /\.(html|sml|pug|jade)/.test(ext)
}

const parse = {
  sync: function (node, src) {
    src =  cache.sync(src, 'uft8')

    node.tag = false
    node.content = filter(src) ? parser(src) : cache.sync(src)

    return node
  },
  async: function (node, src) {
    return cache(src, 'utf8')
      .then((src) => filter(src) ? parser(src) : src
      .then((src) => {
        node.tag = false
        node.content = src
      })
  }
}
```

? @voischev @mrmlnc 

Maybe add `options.filter``

**Comment by mrmlnc** [comment]
I really don't understand why you don't want to use `raw` attribute and create a new tag (`import`) and `filter` option.

For example:

```js
return (node.attrs && node.attrs.raw) ? src : parser(src)
```

**Comment by michael-ciniawsky** [comment]
I like the `node.attrs.raw` idea 

```html
<include src="" raw></include>
```

```js
if (node.attrs.src && node.attrs.raw) return src
```
Just the nitpicking implementation details here :)

```html
<import src=""></import>
```
Is just my nerdy preference and the dead sentence to `posthtml-import`

**Comment by michael-ciniawsky** [comment]
@voischev Can we basically proceed in that way ? :)

**Comment by voischev** [comment]
I would like to include inserted content file without processing by default :( but if you vote for this – ok

**Comment by michael-ciniawsky** [comment]
@voischev Ok I made it with ```node.attrs.raw``` but can try to avoid the extra attr and do it programmatically :), or you try after merge. When recursive includes work I will make PR ok ? 

Current status

#### Done 

- [x] Cutom Parser
- [x] Raw Includes
- [x] Absolute Includes (options.root)
- [x] Relative Includes  {options.relative}
- [x] Sync && Asnyc Plugin
- [x] Add Include (tree.messages)

#### WIP

- [] Recursive Includes (e.g  like [posthtml-modules](https://github.com/posthtml/posthtml-modules/blob/master/index.js#L53) @canvaskisa :)
- [] Add Correct Error (tree.messages)


#### Code
```js
// ------------------------------------
// #POSTHTML - INCLUDE - INDEX
// ------------------------------------

'use strict'

const cache = require('read-cache')

const resolve = require('path').resolve
const dirname = require('path').dirname
const extname = require('path').extname

// const existsSync = require('fs').existsSync

let parser = require('posthtml-parser')

const parse = {
  sync: function (node, src, parser) {
    src = cache.sync(src, 'utf8')

    node.tag = false
    node.content = parser ? parser(src) : src

    return node
  },
  async: function (node, src, parser) {
    return cache(src, 'utf8')
      .then((src) => parser ? parser(src) : src)
      .then((content) => {
        node.tag = false
        node.content = content
      })
  }
}

module.exports = function (options) {
  options = options || { root: process.cwd(), relative: true, async: true }

  return function posthtmlInclude (tree) {
    if (!tree.messages) tree.messages = []

    options.relative ? options.root = dirname(tree.options.from) : options.root

    const includes = []

    tree.match([ { tag: 'include' }, { tag: 'import' } ], (node) => {
      let src

      try {
        src = resolve(options.root, node.attrs.src)
      } catch (error) {
        src = false
        
        // We need a module for PostHTML Warning/Error handling in the near future :)
        tree.messages.push({
          type: 'error',
          error: `[posthtml-include]:\n 
            ${tree.options.from}:\n 
            Include could not be loaded\n 
            ${error}
          `
        })
      }

      if (src) {
        if (extname(src) !== '.html' && tree.options.parser) {
          parser = tree.options.parser
        }

        if (options.sync) {
          return parse.sync(node, src, parser)
        }
        // TODO: refactor to includes raw programmtically here
        if (node.attrs.raw) {
          parser = false
        }

        includes.push(parse.async(node, src, parser))

        tree.messages.push({ type: 'dependency', file: src })
      }

      return node
    })

    return includes.length > 0 ? Promise.all(includes).then(() => tree) : tree
  }
}
```

**Comment by voischev** [comment]
👍

**Comment by michael-ciniawsky** [comment]
@voischev  @mrmlnc  @posthtml/collaborators  Everybody fine with providing the tag as second attr for raw includes? This is the last missing piece before I can finally make PR for v2.0.0

```html
<include src="critical.css" style>
<include src="critical.js" script id="critcal">
```

```html
<style>..Contents</style>
<script id="critical">..Contents</script>
```

**Comment by michael-ciniawsky** [comment]
Would also integrate well with `posthtml-content`

```
<include src="article.md" article md>
```

```
<article md>Markdown handled by posthtml-content/posthtml-md afterwards :)</article>
```

**Comment by GitScrum** [comment]
@michael-ciniawsky 
```html
<include src="critical.css" style>
<include src="critical.js" script id="critcal">
```

this is strange use tag `include` for tag `script` and `style`. why ?

**Comment by michael-ciniawsky** [comment]
> this is strange use tag include for tag script and style. why not be use script, style, markdown with attrs ?

@GitScrum `<include src=""></include> || <import src=""></import>` is the 'plugin' tag, defining an include or import, the examples above are prototypes for raw (in terms of `!== (.html|.sml|.pug)`)
includes. Since the include tag is normally replace with the html of the respective include, thats perfectly fine, but for raws we need a way to set `node.tag = 'include' => node.tag = 'new'` somehow :)

**Comment by michael-ciniawsky** [comment]
Do my propsal was to set the new tag name as the second attr of the include tag, but other/better solution highly welcome 😛

**Comment by GitScrum** [comment]
@michael-ciniawsky 
`<include style="path/to/style.css">` 
`<include script="path/to/script.js">`
`<include markdown="path/to/readme.md">`

**Comment by michael-ciniawsky** [comment]
👍

**Comment by michael-ciniawsky** [comment]
cc @voischev @posthtml/collaborators

**Comment by mrmlnc** [comment]
IMO, `include` should not work with Markdown. I agree that need to be able to wrap styles and script in tags, but not Markdown. For Markdown PostHTML have `posthtml-content` plugin.

Will clarify my original idea with your comments:

  1. User can include any files with `raw` attribute.
  2. User can include styles or scripts files with `style=` or `script=`. Because we need to wrap them in tags.

**Comment by michael-ciniawsky** [comment]
> User can include any files with raw attribute.
> IMO, include should not work with Markdown. 

🤔 😛 I get what you meant, that would just include the **raw** `file.md` and parsing/transfoming is done afterwards with e.g posthtml-content if needed. 

>  Because we need to wrap them in tags

@mrmlnc Yep exactly, thats why I came back here asking for the implementation mostly liked here :)

```html
<include name="file.ext" id="foo" class="bar baz" [transform*]></include>
```

* e.g `posthtml-content`

```html
<name  id="foo" class="bar baz" [transform*]>...file.ext</name>
```

**Comment by mrmlnc** [comment]
Friendly ping to @michael-ciniawsky 🏓

**Comment by michael-ciniawsky** [comment]
@mrmlnc  need to make a small PR to posthtml/posthtml first 😛 . Besides that and Recursive Includes everthing is finished, I'm commited to webpack documentation updates atm, but I do it as quickly as possible, I absolutely need this update aswell.  A bit more time please 🙏. Meanwhile you can `npm i -D michael-ciniawsky/posthtml-include` and test the crap out of it :)

**Comment by michael-ciniawsky** [comment]
@mrmlnc I would like to close this in favour of [#4](https://github.com/posthtml/posthtml-content/pull/4). Ok 😛 ?

**Comment by mrmlnc** [comment]
A small clarification: the link leads to the `posthtml-content` repository, it's correct?

**Comment by michael-ciniawsky** [comment]
@mrmlnc Yep 😛. Feedback/Review there also pls when time 🙏

**Comment by marcofugaro** [comment]
I also would like a `raw` attribute, coming from PHP I want to be able to do something like this:
```html
<include src="partials/head.html" raw></include>

Hello World!

<include src="partials/footer.html" raw></include>
```
Right now, this doesn't work because the parser automatically closes the `body` and `html` tag I opened in the `head.html`, ironically giving me invalid html.

Good job @michael-ciniawsky if you already did it, do a PR

**Comment by michael-ciniawsky** [comment]
> Right now, this doesn't work because the parser automatically closes the body and html tag I opened in the head.html, ironically giving me invalid html.

@marcofugaro Closes the in `body`and `html` tag included in your partials 👀 ? Can you show me the markup in `partials/head.html` && `partials/footer.html`?  The following ways to implement`raw` are under 'consideration'.

### via `posthtml-include`

`<include tag="path/to/file.ext"></include>`

```html
// attr name is the tag name containing the raw value after importing

<include style="path/to/file.css></include>
<include article="path/to/file.txt></include>
```
```
<style>...css</style>
<article>..txt</article>
```

`<include src="path/to/file.ext raw></include>`

```html
// set raw value as the parent nodes content

<article><include src="path/to/file.txt" raw></include></article>
```
```html
<article>...txt</article>
```

### via `posthtml-content`

I also brought up the idea implementing this with another plugin (posthtml-content), to enable tranforms on import `e.g markdown`.

```html
<article md="path/to/article.md"></article>"
```

```js
import posthtml form 'posthtml'
import content form 'posthtml-content'

import marked from 'marked'

const options = { md: (file) => marked(file) }

posthtml([ content(options) ])
  .process(html, { from: './src/index.html' })
  .then((result) => result)
```

```html
<article>
  <h1>Title</h1>
  <p>lorem<a href="">ipsum</a><p>
  ... 
<article>
```

The last is my personal preference atm, since content handling is it's propose anyways, in my opinion `posthtml-include`should only include markup related files (HTML etc.). But feedback/ concerns on this issue are highly welcome and nothing is set in stone yet 😛 , both plugins have PR open, pending to wait for `messages/result.messages` support in posthtml itself [#149](https://github.com/posthtml/posthtml/pull/195) (error, warnings, **dependency (file/includes) tracking and watching**).

**Comment by marcofugaro** [comment]
@michael-ciniawsky sure, [here](https://github.com/marcofugaro/testarossa/blob/master/src/index.html) is where I took the code from, you can check the output by running `npm install` and then `npm run build`, basically it adds `</body></html>` at the end of `_head.html` and removes it from the footer.

Personally between the first two I prefer the `raw` attribute, since I think `src` with the path is more semantically correct.

Regarding transformed includes, when I first installed this plugin I thought the raw option was enabled by default, I didn't know my html was gonna be parsed. I saw this plugin as a way to include anything in my html, not just html. I'm ok with this plugin handling also basic transformed includes, since it's not called `posthtml-include-html`. In my opinion this could be done with `style` or `md` attributes, as proposed previously in this thread. But I'm ok if you decide to delegate `md` to `posthtml-content`.

If it's of any help, as a end-user i see myself using this plugin for including html **components** (what this plugin is designed for), **partials** (what I'm trying to do), and the occasional **inline svg** (which I want to keep in my images folder):
```html
<include src="images/icons/hamburger.svg" raw></include>
```

**Comment by michael-ciniawsky** [comment]
@marcofugaro The initial HTML structure should be in `index.html`. Open tags expecting an closing tag `e.g html, head, body` (non self-closing) will always be closed by the parser and therefore it's not really possible to keep them open between different files/partials. You could set them as self-closing but it will always be kind of hackish that way, I would not advice it.

```html
<html>
 <include src="partials/_header.html"></include>
 <body>
   <include src="partials/_footer.html"></include>
 </body>
</html>
```
> Personally between the first two I prefer the raw attribute, since I think src with the path is more semantically correct.

Agreed a simple `raw` attribute either in `posthtml-include`or `posthtml-content` to import the files plain content is the cleanest solution. Still need to think && test if where to implement at best, e.g the `posthtml-content` approach would be

```
|– components
|    |– partial.html
| – contents
|    |– article.md
|    |– article.txt
|
|– index.html
|– posthtml.config.js
```

**partial.html**

⚠️ Conent paths must be declared relative to `index.html` in partials

```html
<div>
  <article md="./contents/article.md"></article>
  <article raw="./contents/post.txt"></article>
<div>
```

**index.html**
```html
<html>
  <body>
     <include src="./components/partial.html"></include>
  </body>
</html>
```
```js
// raw attribute works out-of-the-box in posthtml-content
posthtml([ include(), content({ md: (md) => marked(md) }) ])
  .process(html, { from: 'src/index.html' })
  .then((result) => result.html)
```

**result.html**

```html
<html>
  <body>
     <div>
        <article>
          <h1>Title</h1>
          <p>Lorem...<p>
        </article>
        <article>Lorem...</article>
      <div>
  </body>
</html>
```

> If it's of any help, as a end-user i see myself using this plugin for including html components (what this plugin is designed for), partials (what I'm trying to do), and the occasional inline svg (which I want to keep in my images folder)

If distinguishing between `components/partials` was meant in terms of `layouts/extends` maybe take a look at posthtml-extend (jade-like) :). For Inline SVG thats actually what I wanted to refer to earlier when saying `Should support Markup(HTML/XML) based includes only`. XML(SVG) gets parsed with the current parser and behaves like and HTML include in this case

**icon.svg**
```svg
<svg>
  <path d="..."></path>
</svg>
```

**index.html**
```html
...
<body>
  <include src="./assets/icon.svg"></include>
</body>
...
```

Albeit there would be plenty of room making a plugin for SVG includes itself e.g handle/support sprites/`<use xlink:href="#icon-1" />` etc. 😛

**Comment by marcofugaro** [comment]
Thanks for your help @michael-ciniawsky! 

Yup, good job on the pull request, also as you say svg support would be ideal since it's valid XML! Can't wait for that!

**Comment by voischev** [comment]
ok) 
> non-parsed files

resolves in posthtml-content plugin? Close issue?

**Comment by michael-ciniawsky** [comment]
@voischev yep, if anyone has concerns/ideas/improvements/bugs etc. => discussion/report @ #16, [#4](https://github.com/posthtml/posthtml-content/pull/4) 😛
