### ISSUE TITLE
feat(index): Multi-level includes

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml-include#18]
Probably would be useful:

_index.html:_
```html
<h1>index</h1>
<include src="includes/1.html"></include>
```
_1.html:_
```html
<h2>1</h2>
<include src="includes/2.html"></include>
```
_2.html:_
```html
<h2>2</h2>
```

**Comment by FDiskas** [comment]
And? ...

**Comment by Scrum** [comment]
what do you expect?

**Comment by FDiskas** [comment]
Solution. The include should work same as js `import from`

**Comment by Scrum** [comment]
@FDiskas may be PR ?

**Comment by FDiskas** [comment]
It's closed for some reason https://github.com/posthtml/posthtml-include/pull/16

**Comment by Scrum** [comment]
@andreyvolokitin @FDiskas @vivaxy @alexreg @equinusocio 🚀
