### ISSUE TITLE
Is it possible for PostHTML plugins to work in included pages?

### ISSUE THREAD

**Issue by egeesin** [posthtml/posthtml-include#21]
Is there any possibility to parse other plugins like posthtml-md, posthtml-lorem in not root page but included pages? If isn't, will there be any plans for that?

**Comment by Scrum** [comment]
it is not entirely clear what you want?

**Comment by GrosSacASac** [comment]
Is it possible to include html and process those included files with other post html plugins ? Those other post html plugins should not run on the root html file.

Considering posthtml-lorem  `require('posthtml-lorem')()`

## index.html

```
<html>
<head>
    <title>index.html</title>
</head>
<body>
	<p lorem="2"></p>
    <include src="components/button.html"></include>
</body>
</html>
```

## components/button.html

`<button class="button"><p lorem="2"></p></button>`

## result

```
<html>
<head>
  <title>index.html</title>
</head>
<body>
	<p lorem="2"></p>
  <button class="button">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </button>
</body>
</html>
```

Note the `<p lorem="2"></p>` in the root `index.html` was not parsed

**Comment by egeesin** [comment]
@Scrum I'm sorry, English isn't my first language. What I want is exactly GrosSacASac wrote above.

**Comment by hacknug** [comment]
This is exactly what I'm doing in a project. What you need to do is make sure you're requiring your plugins in the exact order you want them to run. So in my case I include `posthtml-include` before `posthtml-expressions`.

My `posthtml.config.js` looks like this:

```js
module.exports = {
  plugins: [
    require('posthtml-include')({ root: 'src' }),
    require('posthtml-expressions')({}),
  ],
}
```

**Comment by egeesin** [comment]
This answers my question, thanks @hacknug .
