### ISSUE TITLE
Loops & data

### ISSUE THREAD

**Issue by bre7** [posthtml/posthtml-include#22]
Is there a way to achieve what [gulp-file-include](https://github.com/coderhaoxin/gulp-file-include) offers ?

E.g.

```html
<body>
  @@loop("loop-article.html", "data.json")
</body>
```

Or is such functionality out of the scope of the project ?

**Comment by Scrum** [comment]
@bre7 Hi, use [posthtml-expressions](https://github.com/posthtml/posthtml-expressions) and [posthtml-extend](https://github.com/posthtml/posthtml-extend). [Demo](https://github.com/inside-demo/posthtml-expression-demo)

**Comment by bre7** [comment]
Thanks
