### ISSUE TITLE
Indentation lost

### ISSUE THREAD

**Issue by alexreg** [posthtml/posthtml-include#23]
The indentation for all included lines after the first is lost. It would be nice to maintain this, or at least have an option to do so.

**Comment by Scrum** [comment]
@alexreg  Hi, perhaps you need a plugin [posthtml-beautify](https://github.com/Scrum/posthtml-beautify)

**Comment by alexreg** [comment]
Thanks for pointing that out; it looks useful. That said, this feels like something that should be built in still.

**Comment by Scrum** [comment]
This should not be part of the `include` they have different functionality

**Comment by Scrum** [comment]
@Scrum may be close this issue ?

**Comment by Scrum** [comment]
@alexreg  may be close this issue ?
