### ISSUE TITLE
Allow self-closing `<include ... />` tag

### ISSUE THREAD

**Issue by alexreg** [posthtml/posthtml-include#24]
This makes more sense compared to `<include ...></include>`.

**Comment by Scrum** [comment]
@alexreg Hi, use options for posthtml [singletags](https://github.com/posthtml/posthtml-render#singletags)

**Comment by alexreg** [comment]
Thanks. I don't think this does what I want though. Shouldn't PostHTML just have built-in support for self-closing tags, like `<img />`?

**Comment by Scrum** [comment]
it has a list of self-closing tags according to the documentation, it is not `include` in this list)

**Comment by alexreg** [comment]
Shouldn't `include` be added then?

**Comment by Scrum** [comment]
no, because this is the specificity of the render
