### ISSUE TITLE
Relative imports not working

### ISSUE THREAD

**Issue by FDiskas** [posthtml/posthtml-include#26]
Still not works. 
```
posthtml-include@1.2.0
```
```
└── src
    ├── assets
    │   └── styles
    │       ├── main.scss
    │       └── shared
    │           └── _variables.scss
    ├── components
    │   ├── button
    │   │   └── button.html
    │   └── footer
    │       └── footer.html
    ├── layout
    │   ├── mainLayout.html
    │   └── main.scss
    └── pages
        ├── index.html
        └── landing.html
```
**pages/landing.html**
```html
<include src="../layout/mainLayout.html"></include>
```
**ERROR**
```
🚨  /Projects/src/pages/landing.html: ENOENT: no such file or directory, open '/Projects/layout/mainLayout.html'
```
**.posthtmlrc.js**
```js
const path = require("path");

module.exports = {
    plugins: {
        "posthtml-extend": {
            root: path.resolve(__dirname, "src")
        },
        "posthtml-include": {
            root: path.resolve(__dirname, "src")
        },
        "posthtml-modules": {
            root: path.resolve(__dirname, "src")
        },
        "posthtml-expressions": {
            locals: {}
        }
    }
};
```
Demo reppo: https://github.com/FDiskas/trink
_Originally posted by @FDiskas in https://github.com/posthtml/posthtml-include/issues/1#issuecomment-498255242_

**Comment by FDiskas** [comment]
Why this is important? It is for better IDE "go to definition/follow the link" functionality

**Comment by Scrum** [comment]
```js
"posthtml-include": {
    root: path.resolve(__dirname, "src")
},
```

```html
<include src="../layout/mainLayout.html"></include>
```

you are trying to take a `mainLayout.html` relative to the root `src`

it should work for you

```html
<include src="layout/mainLayout.html"></include>
```

**Comment by FDiskas** [comment]
It works as in documentation but not relative paths

**Comment by FDiskas** [comment]
Why it's closed? It should be converted to feature request instead. Everybody is using relative paths only here is some magic going on

**Comment by Scrum** [comment]
Indeed, you are using a relative path but do not forget that in the option you specified the `root` directory for which you are including

**Comment by FDiskas** [comment]
I tried remove the settings for the root, same results

**Comment by Scrum** [comment]
Put an example on the githab and I'll see what the problem is

**Comment by FDiskas** [comment]
[1559745447316.zip](https://github.com/posthtml/posthtml-include/files/3257659/1559745447316.zip)

**Comment by Scrum** [comment]
you can’t create a repository and put the contents of the source there, I don’t really like to download incomprehensible files

**Comment by FDiskas** [comment]
https://github.com/FDiskas/trink

**Comment by Scrum** [comment]
Explain which of these options should work and why it should work like this
```html
<include src="src/layout/mainLayout.html"></include>
<include src="../layout/mainLayout.html"></include>
<include src="/src/layout/mainLayout.html"></include>
```

**Comment by FDiskas** [comment]
All of them should work.

1. First is included from root in settings root is `/`
1. Should also work, because it is relative path from current file
1. Also should work - the `/` by default means root path

Image this as js `import` :arrow_right:

**Comment by FDiskas** [comment]
It could help you https://nodejs.org/docs/latest/api/path.html#path_path_isabsolute_path

**Comment by Scrum** [comment]
> It could help you

thank you, but I know what an absolute path is and what a relative is

```js
"posthtml-include": {
    root: path.resolve(__dirname, "src")
},
```

if you specify via options, the above example will be resolved as:

root => `/home/project/myproject/src`
src/layout/mainLayout.html => `/home/project/myproject/src/src/layout/mainLayout.html`
../layout/mainLayout.html => `/home/project/layout/mainLayout.html`
/src/layout/mainLayout.html => `/src/layout/mainLayout.html`

or without options

src/layout/mainLayout.html => `/home/project/myproject/src/layout/mainLayout.html`
../layout/mainLayout.html => `/home/project/myproject/layout/mainLayout.html`
/src/layout/mainLayout.html => `/src/layout/mainLayout.html`

What is wrong with you?

**Comment by FDiskas** [comment]
I added demo repo with no options. Did you even looked? Commented lines not working, but shod

**Comment by Scrum** [comment]
you do not understand how the search for the included files goes, see above the results that you will receive and understand your mistakes

**Comment by FDiskas** [comment]
Show example of relative includes please

**Comment by Scrum** [comment]
see https://github.com/posthtml/posthtml-include/issues/26#issuecomment-499898279

**Comment by FDiskas** [comment]
Your example is relative to project root not by current file. :bread:

**Comment by Scrum** [comment]
there should always be a root directory otherwise the probability of infinite recursion is great

**Comment by FDiskas** [comment]
Root by default should be where package.json is located

**Comment by Scrum** [comment]
> Root by default should be where package.json is located

and there is

**Comment by FDiskas** [comment]
So why `../layout/mainLayout.html` with no options does not works?

**Comment by FDiskas** [comment]
And html code looks strange :D
```
<link rel="stylesheet" href="../assets/styles/main.scss" />
<include src="layout/mainLayout.html"></include>
```

**Comment by Scrum** [comment]
@jeremysawesome Years later it seems more logical. After re-reading the comments above, I want to apologize @FDiskas  for abrupt impudence and lack of involvement.

Now this seems trivial as a solution in the form of a separate option. If you already have a PR, I will be glad to accept it, otherwise please be patient)
