### ISSUE TITLE
To long deprecation line

### ISSUE THREAD

**Issue by FDiskas** [posthtml/posthtml-include#27]
https://github.com/posthtml/posthtml-include/blob/e4f2a57c2e52ff721eed747b65eddf7d7a1451e3/index.js#L21-L23

This plugin is not always used by webpack. Message should be shorter and more clear.

**Comment by Scrum** [comment]
may be PR ?

**Comment by FDiskas** [comment]
And for example I'm not using `webpack` for bundling. This should not be bundler specific message
I'm using `parcel` https://github.com/FDiskas/trink

**Comment by Scrum** [comment]
parcel creates its own config which then combines

https://github.com/parcel-bundler/parcel/blob/5200ecceec4e26335e1f9763bc1e5472eb0017b7/packages/core/parcel-bundler/src/transforms/posthtml.js#L39-L47
