### ISSUE TITLE
Include with children support

### ISSUE THREAD

**Issue by Tauka** [posthtml/posthtml-include#32]
### Supporting children for include will enable us to create dynamic html blocks
Example
```html
<div>
  <include src="./button.html"> New button </include>
</div>

<!-- button.html -->
<button class="button"> { $children } </button>

<!-- parsed.html -->
<div>
  <button class="button"> New button </button>
</div>
```

It will allow us create reusable html snippets, rather than hardcoding them

**Comment by Scrum** [comment]
@Tauka Hi, maybe it’s for you [posthtml-modules](https://github.com/posthtml/posthtml-modules) ?

**Comment by Tauka** [comment]
Hello @Scrum! It looks like just what I need! Thank you, I'll try that package

It's a bid odd though that there are two `posthtml` plugins with very similar capabilities

**Comment by Tauka** [comment]
I'm closing this issue for now
