### ISSUE TITLE
<include> clears rest of <p>

### ISSUE THREAD

**Issue by Znarkus** [posthtml/posthtml-include#40]
I have a weird issue where a <include> clears the rest of the <p> tag.
This is the structure:

sales.html
```
<include src="partial/contact-section.html" locals='{"department":"sales"}'></include>
```

partial/contact-section.html
```
<p>
      <include src="partial/phone.html"></include>
      <br>
      <a href="mailto:email@company.com">email@company.com</a>
    </p>
```

partial/phone.html
```
<a href="callto:+123456">+123456</a>
```

Expected result:
```
<p>
      <a href="callto:+123456">+123456</a>
      <br>
      <a href="mailto:email@company.com">email@company.com</a>
    </p>
```

Result:
```
<p>
      <a href="callto:+123456">+123456</a>
    </p>
```

**Comment by Scrum** [comment]
@Znarkus Hi, thanks for your report, I will try to do this soon

**Comment by Znarkus** [comment]
@Scrum In my case, the work-around is to add a `<span>` around the `<include`, but hopefully there is a better solution :) I looked at the code, but I don't really know how posthtml works behind the scenes yet

**Comment by Scrum** [comment]
@Znarkus Hi, I created a [test](https://github.com/posthtml/posthtml-include/pull/43) for your scenario and they pass. Please give more information about the occurrence of your error and lay out an example of reproduction on a github.

thanks

**Comment by Znarkus** [comment]
Thanks. I adjusted the test in this PR https://github.com/posthtml/posthtml-include/pull/44
The issue seems to happen when locals are used.

**Comment by Scrum** [comment]
@Znarkus This related to an error in https://github.com/posthtml/posthtml-render/pull/33

**Comment by Znarkus** [comment]
Thank you for taking the time to fix it!

**Comment by Znarkus** [comment]
I can confirm that 1.4.3 fixed this for me in my project as well
