### ISSUE TITLE
include locals don't merge with posthtml-expressions config locals 

### ISSUE THREAD

**Issue by danielrob** [posthtml/posthtml-include#51]
It would be great to be able to 
.posthtmlrc
```
"posthtml-expressions": {
  "locals": {
    "href_prefix": "/"
  }
},
```
.index.html
```
<include src="site-header.html" locals='{"page": "index"}'></include>
```
And still have access to both `page` and `href_prefix` inside of the site-header.html include. 

Currently, `href_prefix` will be overwritten and become `undefined`. 

The only workaround I could find is to e.g. `<include src="site-header.html" locals='{"href_prefix": "{{href_prefix}}","page": "index"}'></include>` which is a little cumbersome. 

**Versions**
```
    "posthtml-expressions": {
      "version": "1.4.1",
    },
    "posthtml-include": {
      "version": "1.4.3",
    }
```

**Comment by Scrum** [comment]
@danielrob Could you create an example on github so I can reproduce it?

**Comment by Scrum** [comment]
@danielrob Maybe it suits you better https://github.com/posthtml/posthtml-modules#locals

**Comment by verhulstd** [comment]
@danielrob How did you fix this? the global defined still do not merge in the local defined ones....

**Comment by danielrob** [comment]
@verhulstd I'd have to do a lot of digging... was a long time ago now. Sorry!

**Comment by gbronca** [comment]
Have you found a way around it? I'm having the same issue with a project. I've tried posthtml-include and posthtml-modules.

**Comment by Scrum** [comment]
> Have you found a way around it? I'm having the same issue with a project. I've tried posthtml-include and posthtml-modules.

Hi, I've already fallen out of context, could you create a repository to reproduce the problem?

**Comment by gbronca** [comment]
Hi,

A.html

```html
<include
	src="./src/partials/_head.html"
	locals='{
		"title": "Building Your Personal Brand",
		"image": "/src/assets/brand.jpg"
	}'
></include>
```

_head.html
```html
<meta property="title" content="{{ title }}" />
<if condition="{{image}}">
	<meta property="og:image" content="{{ image }}" />
</if>
<else>
	<meta property="og:image" content=".src/assets/logo.jpg" />
</else>
```

The `{{ image }}` inside the <if> tag is always undefined as it doesn't get passed down from the <include> in the caller HTML.

**Comment by danielrob** [comment]
@gbronca that looks like a different issue. That should work. The issue is when global variables from the .posthmlrc are defined, that those variables don't get passed in a case like you posted when other locals are provided.

**Comment by gbronca** [comment]
@danielrob what I get from the variable in the <if> block is undefined. If I move the meta property outside the if block it works fine.

**Comment by lydell** [comment]
For me, the key to success was to:

1. Switch to posthtml-modules
2. Pass the same `locals` to both posthtml-modules and posthtml-expressions:

```json
{
  "plugins": {
    "posthtml-modules": {
	  "locals": {
		"foo": 1
	  }
	},
    "posthtml-expressions": {
	  "locals": {
		"foo": 1
	  }
	}
  }
}
```

In my case I have a `postcss.config.js` so I could just move `locals` to a variable.

**Comment by Scrum** [comment]
publish v1.7.2
