### ISSUE TITLE
Can't Get Example Running

### ISSUE THREAD

**Issue by john01dav** [posthtml/posthtml-include#52]
I'm new to web development (with a background in game and systems programming), so it's plausible that I'm using this tool incorrectly, but I can't get the example in the README to work. When I run `node main.js` (where I put the JS example code) in a directory with a package.json and `includE` and `posthtml-include` both listed, I get the following error:
```
$ node main.js    I have two things to say about this:

(node:2712) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:122:11)
    at Object.join (path.js:1039:7)
    at findProjectRoot (/tmp/posthtml/node_modules/include/include.js:24:37)
    at /tmp/posthtml/node_modules/include/include.js:44:23
    at /tmp/posthtml/node_modules/posthtml/lib/index.js:213:14
    at tryCatch (/tmp/posthtml/node_modules/posthtml/lib/index.js:296:12)
    at PostHTML.<anonymous> (/tmp/posthtml/node_modules/posthtml/lib/index.js:212:15)
    at /tmp/posthtml/node_modules/posthtml/lib/index.js:233:5
    at new Promise (<anonymous>)
    at PostHTML.process (/tmp/posthtml/node_modules/posthtml/lib/index.js:232:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and, notably, no useful output.

Would it be possible to get clarification, ideally in the form of a getting started guide for this project, for how to use this tool?

**Comment by Scrum** [comment]
Hi, there is little information about the error, I took an example (https://github.com/posthtml-issues/posthtml-iclude-issue-52) from the documentation and everything works for me, can you supplement my example (https://github.com/posthtml-issues/posthtml-iclude-issue-52) to reproduce your problem?

**Comment by john01dav** [comment]
I have since moved on from this and I'm using posthtml-include via the posthtml CLI. I'm not sure if you want to keep this open or not, but I'm fine with it being closed.
