### ISSUE TITLE
tree.parser

### ISSUE THREAD

**Issue by hern12** [posthtml/posthtml-include#61]
I found an error tree.parser is not a function. what should I do. thanks

**Comment by sepowitz** [comment]
Also noticing the same thing. Seems to be related to the latest release @1.6.1. I've attached the error output from a recent build attempt via github actions.

![Screen Shot 2021-02-16 at 1 19 55 PM](https://user-images.githubusercontent.com/13374846/108104762-b0783400-7059-11eb-8bf4-25ebd72de8cd.png)

**Comment by hern12** [comment]
For now I just downgrade to 1.6.0
