### ISSUE TITLE
An automated build page not formatted

### ISSUE THREAD

**Issue by QuietJam** [posthtml/posthtml-include#7]
sorry for my english,but when i was using the posthtml-include,i found that the build page con't be aligned correctly,for example:
here is the header.html like this:
`<div class="box1">`
&nbsp; &nbsp;&nbsp;&nbsp;`<div class="box2">test</div>`
`</div>`
and a index.html like:
`<!DOCTYPE html>`
`<html lang="en">`
`<head>`
&nbsp;&nbsp;&nbsp;&nbsp;` <title>test</title>`
&nbsp;&nbsp;&nbsp;&nbsp;`<meta charset="utf-8">`
`</head>`
`<body>`
&nbsp;&nbsp;&nbsp;&nbsp;`<div id="container">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div id="header">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<include src="header.html"></include>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
`</body>`
`</html>`,
then the new build page will be created like:
`<!DOCTYPE html>`
`<html lang="en">`
`<head>`
&nbsp;&nbsp;&nbsp;&nbsp;`<title>test</title>`
&nbsp;&nbsp;&nbsp;&nbsp;`<meta charset="utf-8">`
`</head>`
`<body>`
&nbsp;&nbsp;&nbsp;&nbsp;`<div id="container">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div id="header">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div class="box1">`
&nbsp;&nbsp;&nbsp;&nbsp;`<div class="box2">test</div>`
`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;` </div>`
`</body>`
`</html>`,
is there any solution ? or may be i made some mistake? thanks!

**Comment by voischev** [comment]
Use html beautify after call posthtml. Like https://www.npmjs.com/package/js-beautify

**Comment by andreyvolokitin** [comment]
What is the reason for this behavior?  Could wrong formatting be avoided in the first place or there is no way?

**Comment by michael-ciniawsky** [comment]
One would need to walk the parent node of the `<include>` get the indent and then walk the imported subtree and add the whitespace to all text nodes which could be a perf concern and there is a separate plugin, if a beautified template is desired. Normally the devTools (the browsers HTML Parser) adds the indent when parsing the HTML again or the HTML is hopefully minified anyways for production and the indent doesn't matter :)

**Comment by andreyvolokitin** [comment]
Yep. Though in my case the final output is the actual files which can go to the backend developer, so they better be properly formatted. I am looking at different beautifiers right now, but a little worried that they can introduce their own problems (and they definitely can have quite a bunch of bugs and edge cases). Like I yet to find a beautifier which does not break tags without whitespace between them (```<div>A A</div><div>B B</div>```), they instead wrapping them each on a separate line, though whitespace control between tags can worth a broken layout. So I am worried about handling all my HTML blindly with beautifier with an unknown number of bugs... But I guess there is no choice especially if there is a perf concern
