### ISSUE TITLE
Pass context to partial

### ISSUE THREAD

**Issue by artem-malko** [posthtml/posthtml-include#8]
Is it possible to pass some data (context) to included partial?

**Comment by voischev** [comment]
Write example plz

**Comment by artem-malko** [comment]
Something like that:
```html
<include src="component/button/button.html" context="components/button/data.json"></include>
```
data.json:
```js
{
    "title": "Install"
}
```
And then, in template (button):
```html
<button>{{title}}</button>
```
{{}} or {{{}}} like in handlebars or something like that.

**Comment by voischev** [comment]
it possible. why not use template engines for that, like `Jade`?

**Comment by artem-malko** [comment]
@voischev I would like to use only posthtml if it is possible.

**Comment by voischev** [comment]
@artem-malko if you want, you can make plagin for templating ;)
## simple example
```js
var posthtml = require('posthtml');
var html = '<button>my supper site: {{title}}</button>';

function plugin(tree) {
    var data = { title: 'ololo' };
    var RE = /\{\{(\S+)\}\}/;
    tree.match(RE, function(node) {
        var key = RE.exec(node)[1];
        return node.replace(RE, data[key]);
    });
}

posthtml([plugin]).process(html).then(function(result) {
    console.log('RESULT: ' + result.html);
});
```

**Comment by artem-malko** [comment]
@voischev postCSS style)) Ok, I'll do it)

**Comment by michael-ciniawsky** [comment]
Hey you could consider using [posthtml-exp](https://github.com/michael-ciniawsky/posthtml-exp) for that ;). Partial, Each, Pipe Helpers included, more underway....

**Comment by artem-malko** [comment]
@michael-ciniawsky thanks)
