### ISSUE TITLE
Add head to head

### ISSUE THREAD

**Issue by cedvdb** [posthtml/posthtml-include#82]
I'd expect an element added to the `head` of an included file to be added to the head of the includer.

for example

index.html

```html
<body>
   <include src='footer.html'>
</body>
```

footer.html

```html
<head>
    <link rel='stylesheet' href='/src/scss/footer.scss' />
</head>
<footer></footer>
```

results:

```html

<head>
    <link rel='stylesheet' href='/src/scss/footer.scss' />
</head>
<body>
   <footer></footer>
</body>

**Comment by d892fc** [comment]
That's a too strange feature.

**Comment by sKopheK** [comment]
does not make sense. just include, for example, _head.html_ where you want to have content with `<head>`

**Comment by d892fc** [comment]
Don't forget, there is a "context" variable included.
________________________________
