### ISSUE TITLE
include variable

### ISSUE THREAD

**Issue by cedvdb** [posthtml/posthtml-include#83]
It would be nice to be able to do something like this:

```html
<nav>
  <a href='/' class='{{ page == 'home' ? 'active' : ''}}'>Home</a>
  <a href='./blog.html' class='{{ page == 'blog' ? 'active' : ''}}'>Blog</a>
</nav>
```

**Comment by d892fc** [comment]
I think it is a bad idea. You should do it with some backend language like Java, but not in frontend.

**Comment by cedvdb** [comment]
What makes you think I have a backend. There are tons of better options than using post html for use cases like that. I've used this plugin to have an html & css only website.

**Comment by d892fc** [comment]
Just use some template engine instead, like mustache.
