### ISSUE TITLE
Relative Includes Should be Relative to the HTML File the Include is In

### ISSUE THREAD

**Issue by jeremysawesome** [posthtml/posthtml-include#94]
### Problem

The included files are relative to the root directory, not to the html file. 

### Expectation

Included files should be relative to the html file the include is in.

### Explanation

Relative `posthtml-include` includes do not work the way a typical include in html works. Anytime you construct a path in html it starts from the current html file. This is true for your basic `a`, `img`, `script`, `link` tags. This is how we would expect an `include` tag to work as well.

The following is an excerpt from [this comment](https://github.com/posthtml/posthtml-include/issues/26#issuecomment-1946747240)

Take the following structure.

- 📁 / (root)
	- 📁 project
		 - 📁 src
			- 📁 partials
				- 📄 _partial.html
			- 📁 subpage
				- 📄 index.html
			- 📄 index.html
		- 📄 .posthtmlrc

The inside of `.posthtmlrc` is:

```json
{
  "plugins": {
    "posthtml-include": {
      "root": "./src/"
    }
  }
}
```

Inside of `subpage/index.html` we have the following `<include src="../partials/_partial.html"></include>`

**Expected path**: `/project/src/partials/_partial.html`

One would think that the include would start from `subpage/index.html` and navigate the filesystem from there. The resulting absolute path being `/project/src/partials/_partial.html`. This is how all the other typical includes on an html page work, i.e. `img`, `a`, `link`, `script`, etc...

**Returned Path**: `/project/partials/_partial.html`

It seems that instead of being relative to the `html` file that the `include` is in, the path is relative to whatever the `root` directory is. 

Thus the confusion. 

Any relative path included in `<include src="">` should be relative to the `html` file that the `<include>` tag is placed on. This behavior would match existing relative path behaviors `img`, `a`, `link`, `script`, etc...

**Comment by Scrum** [comment]
> Now this seems trivial as a solution in the form of a separate option. If you already have a PR, I will be glad to accept it, otherwise please be patient)
